import Head from "next/head";
import { useState } from "react";
import SinkModal from "../component/sinkModal";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [cxLeft, setCXLeft] = useState(0);
  const [cxRight, setCXRight] = useState(0);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <SinkModal cxLeft={cxLeft} cxRight={cxRight} />
        <input
          type="range"
          id="right"
          min={0}
          max={150}
          onChange={(event) => {
            const range = parseInt(event.currentTarget.value);
            setCXRight(range);
          }}
        />
        <input
          id="left"
          type="range"
          min={-150}
          max={0}
          onChange={(event) => {
            const range = parseInt(event.currentTarget.value);
            setCXLeft(range);
          }}
        />
      </main>
    </div>
  );
}
